version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/user
      - ./dataset:/docker-entrypoint-initdb.d
    restart: always
volumes:
  postgres-data: