gwizd:
  security:
    auth:
      loginUri: /api/oauth2/authorize
      redirectUri: http://localhost:3000
      logoutUri: /api/oauth2/logout
spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-125.railway.app:8058/railway
    username: postgres
    password: MijRsB9VUz3PzvrUpMnm
    name: railway