spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent-output: true
  servlet:
    multipart:
      max-file-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 320408590575-fiidhhbp7bocnu22rtov41s6llb98e83.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
  mail:
    username: heilmartinos@gmail.com
    password: tqegwigfjdyyecla
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/docs.html
